# Generated by Django 3.1.4 on 2021-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_auto_20210213_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='serials',
            field=models.ManyToManyField(blank=True, related_name='cast', to='serials.Serial'),
        ),
    ]
