# Generated by Django 3.1.4 on 2021-02-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0006_auto_20210213_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='serials',
            field=models.ManyToManyField(related_name='cast', to='serials.Serial'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serials', to=settings.AUTH_USER_MODEL),
        ),
    ]
